# Generated by Django 6.0.8 on 2026-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Pending_Human', 'Pending Human Review'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled'), ('Expired', 'Expired')], default='Pending', max_length=30),
        ),
    ]
